### ISSUE TITLE
Saving English version of task description does not work

### ISSUE THREAD

**Issue by Projekty-TIS-2015-2016** [Chaos-TIS/letna-liga#1]
Login as admin. Edit the English version of task specification. Save changes, say Done, but the database still contains an old version. It was possible to save changes before - when changing only one word in the translation, but changing half of the text (translating it) results in save being unsuccessful. No error is reported during the save, but save doesn't work.

**Comment by Projekty-TIS-2015-2016** [comment]
additional information: 
the following error is printed in the browser javascript console when trying to save:

`Uncaught SyntaxError: missing ) after argument list    addAssignment.php:103`

**Comment by px13** [comment]
fixed.
Problem: special characters were not processed when storing in the database.
